name: b545proj
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - aioeasywebdav=2.4.0
  - aiohttp=3.6.2
  - asn1crypto=1.3.0
  - async-timeout=3.0.1
  - attrs=19.3.0
  - bcrypt=3.1.7
  - blas=1.0
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - cffi=1.14.0
  - chardet=3.0.4
  - cryptography=2.8
  - docutils=0.16
  - dropbox=5.2.1
  - filechunkio=1.6
  - ftputil=3.2
  - hdf5=1.10.2
  - idna=2.9
  - idna_ssl=1.1.0
  - intel-openmp=2019.4
  - kallisto=0.44.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libsodium=1.0.16
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - multidict=4.7.5
  - ncurses=6.2
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1e
  - pandas=1.0.3
  - paramiko=2.7.1
  - pip=20.0.2
  - psutil=5.7.0
  - pycparser=2.20
  - pynacl=1.3.0
  - pyopenssl=19.1.0
  - pysftp=0.2.9
  - pysocks=1.7.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2019.3
  - pyyaml=5.3.1
  - readline=7.0
  - requests=2.23.0
  - setuptools=46.1.1
  - six=1.14.0
  - snakemake=4.0.0
  - sqlite=3.31.1
  - sra-tools=2.8.0
  - tk=8.6.8
  - typing_extensions=3.7.4.1
  - urllib3=1.25.8
  - wheel=0.34.2
  - wrapt=1.12.1
  - xz=5.2.4
  - yaml=0.1.7
  - yarl=1.3.0
  - zlib=1.2.11
